; PlatformIO Projektkonfiguration
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    teemuatlut/TMCStepper @ ^0.7.3
    gin66/FastAccelStepper @ ^0.31.1
    h2zero/NimBLE-Arduino @ ^2.5.1
